import { SalesforceAPI } from '../sf-api.js';
import type {
  OmniBundle,
  BundleEntry,
  OmniElementRecord,
  ImportResult,
} from '../types/bundle.js';

// ─────────────────────────────────────────────────────────────────────────────
// Record helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Strip the `attributes` blob (added by SOQL API) and any null values.
 * Returns a shallow copy — does not mutate the input.
 * Keep for reading/querying; for insert use sanitizeForInsert instead.
 */
function stripRecord(rec: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(rec)) {
    if (k === 'attributes') continue;
    if (v === null) continue;
    out[k] = v;
  }
  return out;
}

/** Escape a string value for use inside a SOQL single-quoted literal. */
function soqlEscape(value: string): string {
  // Backslash must come first, then apostrophe
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

// Fields that Salesforce will reject on insert/update — computed or system-managed.
// Sources:
//   isApiInsertable="false"  → UniqueName, Namespace, EmbeddingPayload (all three entities)
//   auto-generated by SF     → AiGeneratedDescription, GuardrailResults, WebComponentKey
//   unique-key regenerated   → OmniUiCardKey (SF generates a new GUID per record)
const READ_ONLY_FIELDS = new Set([
  // Standard system fields
  'Id', 'CreatedDate', 'CreatedById', 'LastModifiedDate', 'LastModifiedById',
  'SystemModstamp', 'IsDeleted', 'LastActivityDate', 'LastViewedDate',
  'LastReferencedDate',
  // Relationship fields set explicitly by import code (not from the exported data)
  'OmniProcessId', 'ParentElementId', 'OmniDataTransformationId',
  // Internal record attribute added by SOQL API
  'attributes',
  // isApiInsertable="false" in all three entity XMLs
  'UniqueName', 'Namespace', 'EmbeddingPayload',
  // Auto-generated / AI fields — regenerated per org, never copy between orgs
  'AiGeneratedDescription', 'GuardrailResults',
  // Per-org LWC GUID — SF regenerates this on insert
  'WebComponentKey',
  // Unique FlexCard key — SF generates a new one per record (unique index constraint)
  'OmniUiCardKey',
]);

/**
 * Strip read-only/computed fields, null/undefined values, and internal `_*`
 * fields before sending a record to the SF REST API for insert.
 * Returns a shallow copy — does not mutate the input.
 *
 * Note: OmniProcessId and ParentElementId are stripped here because we set
 * them explicitly AFTER calling this function (to the new-org IDs).
 */
function sanitizeForInsert(fields: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(fields)) {
    if (READ_ONLY_FIELDS.has(k)) continue;
    if (v === null || v === undefined) continue;
    if (k.startsWith('_')) continue; // strip _sourceId, _sourceParentId etc
    out[k] = v;
  }
  return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// Topological sort
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Sort entries so dependencies come before the entries that depend on them.
 * Falls back to original order if a cycle is detected.
 */
function topoSort(entries: BundleEntry[]): BundleEntry[] {
  const keyIndex = new Map<string, number>();
  entries.forEach((e, i) => keyIndex.set(e.matchingKey, i));

  const visited = new Set<number>();
  const result: BundleEntry[] = [];

  function visit(idx: number, ancestors: Set<number>) {
    if (ancestors.has(idx)) return; // cycle — skip
    if (visited.has(idx)) return;
    ancestors.add(idx);

    const entry = entries[idx];
    for (const depKey of entry.dependencies ?? []) {
      const depIdx = keyIndex.get(depKey);
      if (depIdx !== undefined) {
        visit(depIdx, ancestors);
      }
    }

    ancestors.delete(idx);
    visited.add(idx);
    result.push(entry);
  }

  for (let i = 0; i < entries.length; i++) {
    visit(i, new Set());
  }

  return result;
}

// ─────────────────────────────────────────────────────────────────────────────
// Per-type import handlers
// ─────────────────────────────────────────────────────────────────────────────

async function importOmniProcess(
  api: SalesforceAPI,
  entry: BundleEntry,
): Promise<ImportResult> {
  const matchingKey = entry.matchingKey;

  if (!entry.process) {
    return { matchingKey, action: 'error', error: 'Missing process data' };
  }

  const isIP = entry.type === 'IntegrationProcedure';
  const proc = entry.process;
  const type = proc.Type;
  const subType = proc.SubType;
  const lang = proc.Language ?? 'English';

  // Find existing versions for versioning and deactivation
  const existingRows = await api.queryAll<{ Id: string; VersionNumber: number; IsActive: boolean }>(
    `SELECT Id, VersionNumber, IsActive FROM OmniProcess WHERE Type = '${soqlEscape(type)}' AND SubType = '${soqlEscape(subType)}' AND Language = '${soqlEscape(lang)}' AND IsIntegrationProcedure = ${isIP} ORDER BY VersionNumber ASC`,
  );
  const existingVersions = existingRows.map((r) => r.VersionNumber);
  const maxVer = existingVersions.length > 0 ? Math.max(...existingVersions) : 0;
  const targetVersion = maxVer + 1;

  // Build fields — sanitize for insert and set computed version
  const processFields = sanitizeForInsert(proc as unknown as Record<string, unknown>);
  processFields['VersionNumber'] = targetVersion;
  processFields['IsActive'] = false; // always insert inactive — user activates via the designer

  // INSERT the process record
  const processId = await api.insert('OmniProcess', processFields);

  // Insert elements level by level (no delete step — this is a fresh record)
  const elements: OmniElementRecord[] = entry.elements ?? [];
  const sourceIdToNewId = new Map<string, string>();
  const maxLevel = elements.reduce((m, e) => Math.max(m, (e.Level as number) ?? 0), 0);

  for (let level = 0; level <= maxLevel; level++) {
    const levelElements = elements
      .filter((e) => ((e.Level as number) ?? 0) === level)
      .sort((a, b) => ((a.SequenceNumber as number) ?? 0) - ((b.SequenceNumber as number) ?? 0));

    for (const el of levelElements) {
      // Read _sourceId / _sourceParentId before sanitizing (they start with '_' and are stripped)
      const rawEl = el as unknown as Record<string, unknown>;
      const sourceId = rawEl['_sourceId'] as string;
      const sourceParentId = rawEl['_sourceParentId'] as string | null | undefined;

      const elFields = sanitizeForInsert(rawEl);

      // Set relationship fields explicitly on the sanitized copy
      elFields['OmniProcessId'] = processId;
      elFields['IsActive'] = true;
      if (sourceParentId) {
        const mappedParentId = sourceIdToNewId.get(sourceParentId);
        if (mappedParentId) {
          elFields['ParentElementId'] = mappedParentId;
        }
      }

      const newId = await api.insert('OmniProcessElement', elFields);
      if (sourceId) sourceIdToNewId.set(sourceId, newId);
    }
  }

  // ── Activation strategy ────────────────────────────────────────────────────
  // Integration Procedures are activated safely via REST PATCH — they are called
  // programmatically at runtime and do NOT require OmniProcessCompilation to be
  // written.  Activating via REST is therefore safe and saves the user from
  // manually activating every IP in a bundle.
  //
  // OmniScripts DO require OmniProcessCompilation for the designer and runtime.
  // We activate via REST PATCH then call the Connect API compile endpoint which
  // writes that row.  If the compile endpoint fails we return a non-fatal note
  // so the user can activate once in the designer to fix the cache.
  if (isIP) {
    // Deactivate any existing active version before activating the new one.
    const activeRows = existingRows.filter((r) => r.IsActive);
    for (const row of activeRows) {
      await api.update('OmniProcess', row.Id, { IsActive: false });
    }
    try {
      await api.update('OmniProcess', processId, { IsActive: true });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (msg.includes('Another active') || msg.includes('FIELD_INTEGRITY_EXCEPTION')) {
        const activeVersions = activeRows.map((r) => r.VersionNumber);
        const activeLabel = activeVersions.length > 0 ? `v${activeVersions.join(', v')}` : 'another version';
        return {
          matchingKey,
          action: 'created',
          id: processId,
          error: `Imported as inactive (v${targetVersion}) — ${activeLabel} is still active. Deactivate it in Salesforce Setup, then activate v${targetVersion}.`,
        };
      }
      throw err;
    }
    return { matchingKey, action: 'created', id: processId };
  }

  // OmniScript — activate via REST, then call the compile endpoint so the
  // designer cache (OmniProcessCompilation) is written correctly.
  // If anything fails here it is non-fatal: the record is imported; the user
  // can open the OmniScript in the designer and click Activate once to fix it.
  const activeRows = existingRows.filter((r) => r.IsActive);
  for (const row of activeRows) {
    await api.update('OmniProcess', row.Id, { IsActive: false });
  }
  try {
    await api.update('OmniProcess', processId, { IsActive: true });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (msg.includes('Another active') || msg.includes('FIELD_INTEGRITY_EXCEPTION')) {
      const activeVersions = activeRows.map((r) => r.VersionNumber);
      const activeLabel = activeVersions.length > 0 ? `v${activeVersions.join(', v')}` : 'another version';
      return {
        matchingKey,
        action: 'created',
        id: processId,
        note: `Imported as inactive (v${targetVersion}) — ${activeLabel} is still active. Deactivate it in Salesforce Setup, then activate v${targetVersion} in the designer.`,
      };
    }
    throw err;
  }

  const compileError = await api.compileOmniScript(processId, lang);
  if (compileError) {
    return {
      matchingKey,
      action: 'created',
      id: processId,
      note: `Imported and activated (v${targetVersion}), but designer compile step failed — open in OmniStudio Setup and re-activate to fix the designer. Compile error: ${compileError}`,
    };
  }

  return { matchingKey, action: 'created', id: processId };
}

async function importOmniUiCard(
  api: SalesforceAPI,
  entry: BundleEntry,
): Promise<ImportResult> {
  const matchingKey = entry.matchingKey;

  if (!entry.card) {
    return { matchingKey, action: 'error', error: 'Missing card data' };
  }

  const cardFields = sanitizeForInsert(entry.card as unknown as Record<string, unknown>);
  const name = cardFields['Name'] as string;
  const authorName = (cardFields['AuthorName'] as string) ?? '';

  // Next available version
  const existingRows = await api.queryAll<{ VersionNumber: number }>(
    `SELECT VersionNumber FROM OmniUiCard WHERE Name = '${soqlEscape(name)}' AND AuthorName = '${soqlEscape(authorName)}' ORDER BY VersionNumber ASC`,
  );
  const maxVer = existingRows.length > 0 ? Math.max(...existingRows.map((r) => r.VersionNumber)) : 0;
  cardFields['VersionNumber'] = maxVer + 1;
  cardFields['IsActive'] = false;

  const id = await api.insert('OmniUiCard', cardFields);
  return { matchingKey, action: 'created', id };
}

async function importDataRaptor(
  api: SalesforceAPI,
  entry: BundleEntry,
): Promise<ImportResult> {
  const matchingKey = entry.matchingKey;

  if (!entry.transform) {
    return { matchingKey, action: 'error', error: 'Missing transform data' };
  }

  const transformFields = sanitizeForInsert(entry.transform as unknown as Record<string, unknown>);
  const name = transformFields['Name'] as string;

  // Next available version (DataRaptor also has VersionNumber)
  const existingRows = await api.queryAll<{ Id: string; VersionNumber: number; IsActive: boolean }>(
    `SELECT Id, VersionNumber, IsActive FROM OmniDataTransform WHERE Name = '${soqlEscape(name)}' ORDER BY VersionNumber ASC`,
  );
  const existingVersions = existingRows.map((r) => r.VersionNumber).filter((v) => v != null);
  const maxVer = existingVersions.length > 0 ? Math.max(...existingVersions) : 0;
  transformFields['VersionNumber'] = maxVer + 1;
  transformFields['IsActive'] = false; // insert inactive first

  const activeTransformRows = existingRows.filter((r) => r.IsActive);
  const activeTransformVersions = activeTransformRows.map((r) => r.VersionNumber);

  // Attempt to deactivate any existing active version.
  // SF may silently ignore this — handled gracefully at activation time below.
  for (const row of activeTransformRows) {
    await api.update('OmniDataTransform', row.Id, { IsActive: false });
  }

  const transformId = await api.insert('OmniDataTransform', transformFields);

  // Insert items (no delete step — fresh record)
  for (const item of entry.transformItems ?? []) {
    const itemFields = sanitizeForInsert(item as unknown as Record<string, unknown>);
    itemFields['OmniDataTransformationId'] = transformId;
    await api.insert('OmniDataTransformItem', itemFields);
  }

  // Activate — separate update required (SF ignores IsActive=true on initial insert).
  // If deactivation of the old version was silently ignored, surface a clear message.
  try {
    await api.update('OmniDataTransform', transformId, { IsActive: true });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (msg.includes('Another active') || msg.includes('FIELD_INTEGRITY_EXCEPTION')) {
      const activeLabel = activeTransformVersions.length > 0 ? `v${activeTransformVersions.join(', v')}` : 'another version';
      return {
        matchingKey,
        action: 'created',
        id: transformId,
        error: `Imported as inactive (v${maxVer + 1}) — ${activeLabel} is already active in this org. Deactivate ${activeLabel} in Salesforce Setup, then activate v${maxVer + 1}.`,
      };
    }
    throw err;
  }

  return { matchingKey, action: 'created', id: transformId };
}

async function importEntry(api: SalesforceAPI, entry: BundleEntry): Promise<ImportResult> {
  const matchingKey = entry.matchingKey;

  try {
    switch (entry.type) {
      case 'OmniScript':
      case 'IntegrationProcedure':
        return await importOmniProcess(api, entry);
      case 'OmniUiCard':
        return await importOmniUiCard(api, entry);
      case 'DataRaptor':
        return await importDataRaptor(api, entry);
      default:
        return { matchingKey, action: 'skipped', error: `Unknown type: ${String(entry.type)}` };
    }
  } catch (err) {
    return {
      matchingKey,
      action: 'error',
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Public entry point
// ─────────────────────────────────────────────────────────────────────────────

export async function importBundle(
  api: SalesforceAPI,
  bundle: OmniBundle,
): Promise<ImportResult[]> {
  const sorted = topoSort(bundle.entries);
  const results: ImportResult[] = [];

  for (const entry of sorted) {
    const result = await importEntry(api, entry);
    results.push(result);
  }

  return results;
}
